spring:
  application:
    name: eureka-server

server:
  port: 10001

eureka:
  instance:
    hostname: peer1

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer2:10002/eureka/
